### ISSUE TITLE
Add a String Reversal Function

### ISSUE THREAD

**Issue by manazpr** [manazpr/chainlink-demo#4]
We need a JavaScript function that takes a string as input and returns the reversed version of that string. The function should reverse the characters in the string while preserving the order of words.

**Comment by pkpndy** [comment]
> We need a JavaScript function that takes a string as input and returns the reversed version of that string. The function should reverse the characters in the string while preserving the order of words.

@manazpr Can I take this?

**Comment by manazpr** [comment]
Sorry, I made it to test an automation. You can contribute to my open-source library @finity-ui

**Comment by pkpndy** [comment]
Sure, Would love to.
